---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baseName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.baseName }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - name: http
    port: 8080
  selector:
    app: {{ .Values.baseName }}
...
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.baseName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.baseName }}.{{ .Values.baseUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.baseName }}
            port:
              name: http
    {{- if .Values.enableIngressTls }}
    tls:
    - hosts:
      - {{ .Values.baseName }}.{{ .Values.baseUrl }}
    {{- end }}
...

